### ISSUE TITLE
CMAKE error when building the project

### ISSUE THREAD

**Issue by yaalyy** [Si1w/LinearAlgebraLibrary#1]
It seems that the repo requires the GTest dependency, and there is no any instruction or notice to tell in the README. However, dockerfile does indicate that GTest has to be installed before using.
Error Log:
Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR
  GTEST_MAIN_LIBRARY)

**Comment by Si1w** [comment]
Readme has been updated
